services:
  - type: web
    name: tracker-service
    env: docker
    plan: free
    buildCommand: "mvn clean package"  # This will run the Maven build first
    startCommand: "java -jar target/tracker-0.0.1-SNAPSHOT.jar"
    healthCheckPath: "/actuator/health"
    autoDeploy: true
