services:
  - type: web
    name: tracker-service
    env: docker
    plan: free
    buildCommand: "mvn clean package"  # This will build the app in Render
    healthCheckPath: "/ping"  # Adjust if necessary for health check
    autoDeploy: true
