services:
  - type: web
    name: tracker-service
    env: docker
    plan: free
    buildCommand: "mvn clean package"  # Build command for the Java app
    healthCheckPath: "/actuator/health"
    autoDeploy: true
