services:
  - type: web
    name: tracker-service
    env: docker
    plan: free
    buildCommand: "./mvnw clean package"
    startCommand: "java -jar target/tracker-0.0.1-SNAPSHOT.jar"
    healthCheckPath: "/actuator/health"
    autoDeploy: true
    envVars:
      - key: PORT
        value: 8080
